CREATE TABLE IF NOT EXISTS Hits
(
    id        bigint   GENERATED BY DEFAULT AS IDENTITY,
    uri      varchar   NOT NULL,
    app varchar   NOT NULL,
    ip varchar   NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE NOT NULL
);